config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Overview of all tasks
  get 'tasks', to: 'tasks#index'

  # Read(one) task (READ)
  get 'task/:id', to: 'tasks#task'

  # Add(one) task (CREATE)
  get 'tasks/add', to: 'tasks#add'
  post 'tasks', to: 'tasks#upload'

  # Update(one) task (UPDATE)
  get 'task/:id/edit', to: 'tasks#edit', as: :edit
  patch 'task/:id', to: 'tasks#update', as: :update

  # Destroy(one) task (DELETE)
  get 'task/:id/destroy', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def task
    @task = Task.find(params[:id])
  end

  def add
    @task = Task.new
  end

  def upload
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/add.html.erb
<h1>My new task</h1>

<%= form_with model: @task do |form| %>
  <%= form.label :title, "Task name:" %>
  <%= form.text_field :title %>
  <%= form.label :details, "Task details:" %>
  <%= form.text_field :details %>
  <%= form.submit "Add task" %>
<% end %>

app/views/tasks/edit.html.erb
<h1> Edit your task </h1>

<%= form_with model: @task, url: "/task/#{@task.id}", method: :patch do |form| %>
  <%= form.label :title, "Task name:" %>
  <%= form.text_field :title %>
  <%= form.label :details, "Task details:" %>
  <%= form.text_field :details %>
  <%= form.button "Update" %>
<% end %>

app/views/tasks/index.html.erb
<h1> List all tasks </h1>

<ul>
<% @tasks.each do |task| %>
  <li><%= link_to task.title, "/task/#{task.id}" %></li>
<% end %>
</ul>

<%= link_to "create new task", "tasks/add" %>

app/views/tasks/task.html.erb
<h1><%=@task.title%> </h1>
<p><%=@task.details%></p>

<%= link_to "update this task", edit_path(@task.id) %>
<%= link_to "remove this task", destroy_path(@task.id) %>